dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
dotenv: .env
networks:
  development:
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
  rinkeby:
    MockV3Aggregator: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    LinkToken: "0x01BE23585060835E02B77ef475b0Cc51aA1e0709"
    VRFCoordinatorMock: "0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B"
    key_hash: "0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311"
    verify: True
wallets:
  rinkeby:
    owner_private_key: ${RINKEBY_OWNER_PRIVATE_KEY}
