dependencies:
  - "aave/protocol-v2@1.0.1"
dotenv: .env
networks:
  development: {}
  rinkeby:
    verify: True
  kovan:
    weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
    lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    dai_eth_price_feed: "0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541"
    dai_token: "0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD"
    verify: True
wallets:
  rinkeby:
    owner_private_key: ${RINKEBY_OWNER_PRIVATE_KEY}
  kovan:
    owner_private_key: ${KOVAN_OWNER_PRIVATE_KEY}
